export const authAction = {
    REGISTER: "REGISTER_USER",
    LOGIN: "LOGIN_USER",
    SUCCESS: "LOGIN_SUCCESS",
    ERROR: "LOGIN_ERROR",
    LOGOUT: "LOGOUT_USER",
    RESUME: "RESUME_SESSION",
};

export const propsAction = {
    ADD_PROP: "ADD_PROPERTY",
    DEL_PROP : "DELETE_PROPERTY", 
    DEL_SUCCESS: "DELETE_SUCCESSFUL",
    EDIT_PROP : "EDIT_PROPERTY",
    UPDATE_PROPS: "UPDATE_PROPERTY",
    UPDATE_SUCCESS: "UPDATE_SUCCESSFUL",
    UPDATE_ERROR: "UPDATE_ERROR",
    SET_SCREEN : "SET_SCREEN",
    GET_SCREEN : "GET_SCREEN",
    UPLOAD_IMAGE : "UPLOAD_IMAGE",
};
