export const properties = [
    {   
        key: '0',
        title: 'Semi-Detached House',
        area: 'Osapa London',
        date: '30 June, 2019',
        category: 'Commercial',
        pType: 'Semi-detached house',
        section: 'sale',
        price: '20,000,000',
        service: '500,000',
        Caution: '600,000',
        beds: '2',
        baths: '3',
        park: '3',
        landSize: '3000sqm',
        propSize: '1800sqm',
        location: '7b Furo Ezimora Street, Lekki Phase 1, Lagos.',
        nearPlace: 'Standard Chartterd bank, Lekki Collisium, Peninsula Hotel, Furn Truf, Ebeano Supermarket....',
        status: 'Completed',
        pTitle: 'C of O',
        leaseTerm: '',
        ePlatform: 'Cortts Website, Nigerian Property Centre, Commercial website',
        floor: '10',
        availFloor: '7th Floor',
        link: 'Owner',
        linkContact: '+234800000000',
        corttsAgent: 'Anita',
        features: 'Fitted Kitchen, Elevator, Swimming pool, Gym,24 hour security and power, Water treatment plant.',
        desc: 'This property is just big jare there is nothing appealing here, nonsense, SMH. Na wa for the landlord chai!! ',
        remark: 'I swear the property is just too expensive is just too expensive funny landlord.',
    },
    {
        key: '1',
        title: 'Terrace House',
        area: 'Banana island',
        date: '04 June, 2019',
        category: 'Commercial',
        pType: 'Semi-detached house',
        section: 'sale',
        price: '20,000,000',
        service: '500,000',
        Caution: '600,000',
        beds: '2',
        baths: '3',
        park: '3',
        landSize: '3000sqm',
        propSize: '1800sqm',
        location: '7b Furo Ezimora Street, Lekki Phase 1, Lagos.',
        nearPlace: 'Standard Chartterd bank, Lekki Collisium, Peninsula Hotel, Furn Truf, Ebeano Supermarket....',
        status: 'Completed',
        pTitle: 'C of O',
        leaseTerm: '',
        ePlatform: 'Cortts Website, Nigerian Property Centre, Commercial website',
        floor: '10',
        availFloor: '7th Floor',
        link: 'Owner',
        linkContact: '+234800000000',
        corttsAgent: 'Anita',
        features: 'Fitted Kitchen, Elevator, Swimming pool, Gym,24 hour security and power, Water treatment plant.',
        desc: 'This property is just big jare there is nothing appealing here, nonsense, SMH. Na wa for the landlord chai!! ',
        remark: 'I swear the property is just too expensive is just too expensive funny landlord.',
    },
    {
        key: '2',
        title: 'High Rise Building',
        area: 'Victoria Island',
        date: '30 May, 2019',
        category: 'Commercial',
        pType: 'Semi-detached house',
        section: 'sale',
        price: '20,000,000',
        service: '500,000',
        Caution: '600,000',
        beds: '2',
        baths: '3',
        park: '3',
        landSize: '3000sqm',
        propSize: '1800sqm',
        location: '7b Furo Ezimora Street, Lekki Phase 1, Lagos.',
        nearPlace: 'Standard Chartterd bank, Lekki Collisium, Peninsula Hotel, Furn Truf, Ebeano Supermarket....',
        status: 'Completed',
        pTitle: 'C of O',
        leaseTerm: '',
        ePlatform: 'Cortts Website, Nigerian Property Centre, Commercial website',
        floor: '10',
        availFloor: '7th Floor',
        link: 'Owner',
        linkContact: '+234800000000',
        corttsAgent: 'Anita',
        features: 'Fitted Kitchen, Elevator, Swimming pool, Gym,24 hour security and power, Water treatment plant.',
        desc: 'This property is just big jare there is nothing appealing here, nonsense, SMH. Na wa for the landlord chai!! ',
        remark: 'I swear the property is just too expensive is just too expensive funny landlord.',
    },
    {
        key: '3',
        title: 'Super Mall',
        area: 'Lekki Phase 1',
        date: '19 May, 2019',
        category: 'Commercial',
        pType: 'Semi-detached house',
        section: 'sale',
        price: '20,000,000',
        service: '500,000',
        Caution: '600,000',
        beds: '2',
        baths: '3',
        park: '3',
        landSize: '3000sqm',
        propSize: '1800sqm',
        location: '7b Furo Ezimora Street, Lekki Phase 1, Lagos.',
        nearPlace: 'Standard Chartterd bank, Lekki Collisium, Peninsula Hotel, Furn Truf, Ebeano Supermarket....',
        status: 'Completed',
        pTitle: 'C of O',
        leaseTerm: '',
        ePlatform: 'Cortts Website, Nigerian Property Centre, Commercial website',
        floor: '10',
        availFloor: '7th Floor',
        link: 'Owner',
        linkContact: '+234800000000',
        corttsAgent: 'Anita',
        features: 'Fitted Kitchen, Elevator, Swimming pool, Gym,24 hour security and power, Water treatment plant.',
        desc: 'This property is just big jare there is nothing appealing here, nonsense, SMH. Na wa for the landlord chai!! ',
        remark: 'I swear the property is just too expensive is just too expensive funny landlord.',
    },
    {
        key: '4',
        title: 'Guru\'s Estate',
        area: 'Parkview ',
        date: '30 Feb, 2019',
        category: 'Commercial',
        pType: 'Semi-detached house',
        section: 'sale',
        price: '20,000,000',
        service: '500,000',
        Caution: '600,000',
        beds: '2',
        baths: '3',
        park: '3',
        landSize: '3000sqm',
        propSize: '1800sqm',
        location: '7b Furo Ezimora Street, Lekki Phase 1, Lagos.',
        nearPlace: 'Standard Chartterd bank, Lekki Collisium, Peninsula Hotel, Furn Truf, Ebeano Supermarket....',
        status: 'Completed',
        pTitle: 'C of O',
        leaseTerm: '',
        ePlatform: 'Cortts Website, Nigerian Property Centre, Commercial website',
        floor: '10',
        availFloor: '7th Floor',
        link: 'Owner',
        linkContact: '+234800000000',
        corttsAgent: 'Anita',
        features: 'Fitted Kitchen, Elevator, Swimming pool, Gym,24 hour security and power, Water treatment plant.',
        desc: 'This property is just big jare there is nothing appealing here, nonsense, SMH. Na wa for the landlord chai!! ',
        remark: 'I swear the property is just too expensive is just too expensive funny landlord.',
    },
    {
        key: '5',
        title: 'Semi-Detached House',
        area: 'Osapa London',
        date: '30 June, 2019',
        category: 'Commercial',
        pType: 'Semi-detached house',
        section: 'sale',
        price: '20,000,000',
        service: '500,000',
        Caution: '600,000',
        beds: '2',
        baths: '3',
        park: '3',
        landSize: '3000sqm',
        propSize: '1800sqm',
        location: '7b Furo Ezimora Street, Lekki Phase 1, Lagos.',
        nearPlace: 'Standard Chartterd bank, Lekki Collisium, Peninsula Hotel, Furn Truf, Ebeano Supermarket....',
        status: 'Completed',
        pTitle: 'C of O',
        leaseTerm: '',
        ePlatform: 'Cortts Website, Nigerian Property Centre, Commercial website',
        floor: '10',
        availFloor: '7th Floor',
        link: 'Owner',
        linkContact: '+234800000000',
        corttsAgent: 'Anita',
        features: 'Fitted Kitchen, Elevator, Swimming pool, Gym,24 hour security and power, Water treatment plant.',
        desc: 'This property is just big jare there is nothing appealing here, nonsense, SMH. Na wa for the landlord chai!! ',
        remark: 'I swear the property is just too expensive is just too expensive funny landlord.',
    },
    {
        key: '6',
        title: 'Terrace House',
        area: 'Banana island',
        date: '04 June, 2019',
        category: 'Commercial',
        pType: 'Semi-detached house',
        section: 'sale',
        price: '20,000,000',
        service: '500,000',
        Caution: '600,000',
        beds: '2',
        baths: '3',
        park: '3',
        landSize: '3000sqm',
        propSize: '1800sqm',
        location: '7b Furo Ezimora Street, Lekki Phase 1, Lagos.',
        nearPlace: 'Standard Chartterd bank, Lekki Collisium, Peninsula Hotel, Furn Truf, Ebeano Supermarket....',
        status: 'Completed',
        pTitle: 'C of O',
        leaseTerm: '',
        ePlatform: 'Cortts Website, Nigerian Property Centre, Commercial website',
        floor: '10',
        availFloor: '7th Floor',
        link: 'Owner',
        linkContact: '+234800000000',
        corttsAgent: 'Anita',
        features: 'Fitted Kitchen, Elevator, Swimming pool, Gym,24 hour security and power, Water treatment plant.',
        desc: 'This property is just big jare there is nothing appealing here, nonsense, SMH. Na wa for the landlord chai!! ',
        remark: 'I swear the property is just too expensive is just too expensive funny landlord.',
    },
    {
        key: '7',
        title: 'High Rise Building',
        area: 'Victoria Island',
        date: '30 May, 2019',
        category: 'Commercial',
        pType: 'Semi-detached house',
        section: 'sale',
        price: '20,000,000',
        service: '500,000',
        Caution: '600,000',
        beds: '2',
        baths: '3',
        park: '3',
        landSize: '3000sqm',
        propSize: '1800sqm',
        location: '7b Furo Ezimora Street, Lekki Phase 1, Lagos.',
        nearPlace: 'Standard Chartterd bank, Lekki Collisium, Peninsula Hotel, Furn Truf, Ebeano Supermarket....',
        status: 'Completed',
        pTitle: 'C of O',
        leaseTerm: '',
        ePlatform: 'Cortts Website, Nigerian Property Centre, Commercial website',
        floor: '10',
        availFloor: '7th Floor',
        link: 'Owner',
        linkContact: '+234800000000',
        corttsAgent: 'Anita',
        features: 'Fitted Kitchen, Elevator, Swimming pool, Gym,24 hour security and power, Water treatment plant.',
        desc: 'This property is just big jare there is nothing appealing here, nonsense, SMH. Na wa for the landlord chai!! ',
        remark: 'I swear the property is just too expensive is just too expensive funny landlord.',
    },
    {
        key: '8',
        title: 'Super Mall',
        area: 'Lekki Phase 1',
        date: '19 May, 2019',
        category: 'Commercial',
        pType: 'Semi-detached house',
        section: 'sale',
        price: '20,000,000',
        service: '500,000',
        Caution: '600,000',
        beds: '2',
        baths: '3',
        park: '3',
        landSize: '3000sqm',
        propSize: '1800sqm',
        location: '7b Furo Ezimora Street, Lekki Phase 1, Lagos.',
        nearPlace: 'Standard Chartterd bank, Lekki Collisium, Peninsula Hotel, Furn Truf, Ebeano Supermarket....',
        status: 'Completed',
        pTitle: 'C of O',
        leaseTerm: '',
        ePlatform: 'Cortts Website, Nigerian Property Centre, Commercial website',
        floor: '10',
        availFloor: '7th Floor',
        link: 'Owner',
        linkContact: '+234800000000',
        corttsAgent: 'Anita',
        features: 'Fitted Kitchen, Elevator, Swimming pool, Gym,24 hour security and power, Water treatment plant.',
        desc: 'This property is just big jare there is nothing appealing here, nonsense, SMH. Na wa for the landlord chai!! ',
        remark: 'I swear the property is just too expensive is just too expensive funny landlord.',
    },
    {
        key: '9',
        title: 'Guru\'s Estate',
        area: 'Parkview ',
        date: '30 Feb, 2019',
        category: 'Commercial',
        pType: 'Semi-detached house',
        section: 'sale',
        price: '20,000,000',
        service: '500,000',
        Caution: '600,000',
        beds: '2',
        baths: '3',
        park: '3',
        landSize: '3000sqm',
        propSize: '1800sqm',
        location: '7b Furo Ezimora Street, Lekki Phase 1, Lagos.',
        nearPlace: 'Standard Chartterd bank, Lekki Collisium, Peninsula Hotel, Furn Truf, Ebeano Supermarket....',
        status: 'Completed',
        pTitle: 'C of O',
        leaseTerm: '',
        ePlatform: 'Cortts Website, Nigerian Property Centre, Commercial website',
        floor: '10',
        availFloor: '7th Floor',
        link: 'Owner',
        linkContact: '+234800000000',
        corttsAgent: 'Anita',
        features: 'Fitted Kitchen, Elevator, Swimming pool, Gym,24 hour security and power, Water treatment plant.',
        desc: 'This property is just big jare there is nothing appealing here, nonsense, SMH. Na wa for the landlord chai!! ',
        remark: 'I swear the property is just too expensive is just too expensive funny landlord.',
    },
    {
        key: '10',
        title: 'Semi-Detached House',
        area: 'Osapa London',
        date: '30 June, 2019',
        category: 'Commercial',
        pType: 'Semi-detached house',
        section: 'sale',
        price: '20,000,000',
        service: '500,000',
        Caution: '600,000',
        beds: '2',
        baths: '3',
        park: '3',
        landSize: '3000sqm',
        propSize: '1800sqm',
        location: '7b Furo Ezimora Street, Lekki Phase 1, Lagos.',
        nearPlace: 'Standard Chartterd bank, Lekki Collisium, Peninsula Hotel, Furn Truf, Ebeano Supermarket....',
        status: 'Completed',
        pTitle: 'C of O',
        leaseTerm: '',
        ePlatform: 'Cortts Website, Nigerian Property Centre, Commercial website',
        floor: '10',
        availFloor: '7th Floor',
        link: 'Owner',
        linkContact: '+234800000000',
        corttsAgent: 'Anita',
        features: 'Fitted Kitchen, Elevator, Swimming pool, Gym,24 hour security and power, Water treatment plant.',
        desc: 'This property is just big jare there is nothing appealing here, nonsense, SMH. Na wa for the landlord chai!! ',
        remark: 'I swear the property is just too expensive is just too expensive funny landlord.',
    },
    {
        key: '11',
        title: 'Terrace House',
        area: 'Banana island',
        date: '04 June, 2019',
        category: 'Commercial',
        pType: 'Semi-detached house',
        section: 'sale',
        price: '20,000,000',
        service: '500,000',
        Caution: '600,000',
        beds: '2',
        baths: '3',
        park: '3',
        landSize: '3000sqm',
        propSize: '1800sqm',
        location: '7b Furo Ezimora Street, Lekki Phase 1, Lagos.',
        nearPlace: 'Standard Chartterd bank, Lekki Collisium, Peninsula Hotel, Furn Truf, Ebeano Supermarket....',
        status: 'Completed',
        pTitle: 'C of O',
        leaseTerm: '',
        ePlatform: 'Cortts Website, Nigerian Property Centre, Commercial website',
        floor: '10',
        availFloor: '7th Floor',
        link: 'Owner',
        linkContact: '+234800000000',
        corttsAgent: 'Anita',
        features: 'Fitted Kitchen, Elevator, Swimming pool, Gym,24 hour security and power, Water treatment plant.',
        desc: 'This property is just big jare there is nothing appealing here, nonsense, SMH. Na wa for the landlord chai!! ',
        remark: 'I swear the property is just too expensive is just too expensive funny landlord.',
    },
    {
        key: '12',
        title: 'High Rise Building',
        area: 'Victoria Island',
        date: '30 May, 2019',
        category: 'Commercial',
        pType: 'Semi-detached house',
        section: 'sale',
        price: '20,000,000',
        service: '500,000',
        Caution: '600,000',
        beds: '2',
        baths: '3',
        park: '3',
        landSize: '3000sqm',
        propSize: '1800sqm',
        location: '7b Furo Ezimora Street, Lekki Phase 1, Lagos.',
        nearPlace: 'Standard Chartterd bank, Lekki Collisium, Peninsula Hotel, Furn Truf, Ebeano Supermarket....',
        status: 'Completed',
        pTitle: 'C of O',
        leaseTerm: '',
        ePlatform: 'Cortts Website, Nigerian Property Centre, Commercial website',
        floor: '10',
        availFloor: '7th Floor',
        link: 'Owner',
        linkContact: '+234800000000',
        corttsAgent: 'Anita',
        features: 'Fitted Kitchen, Elevator, Swimming pool, Gym,24 hour security and power, Water treatment plant.',
        desc: 'This property is just big jare there is nothing appealing here, nonsense, SMH. Na wa for the landlord chai!! ',
        remark: 'I swear the property is just too expensive is just too expensive funny landlord.',
    },
    {
        key: '13',
        title: 'Super Mall',
        area: 'Lekki Phase 1',
        date: '19 May, 2019',
        category: 'Commercial',
        pType: 'Semi-detached house',
        section: 'sale',
        price: '20,000,000',
        service: '500,000',
        Caution: '600,000',
        beds: '2',
        baths: '3',
        park: '3',
        landSize: '3000sqm',
        propSize: '1800sqm',
        location: '7b Furo Ezimora Street, Lekki Phase 1, Lagos.',
        nearPlace: 'Standard Chartterd bank, Lekki Collisium, Peninsula Hotel, Furn Truf, Ebeano Supermarket....',
        status: 'Completed',
        pTitle: 'C of O',
        leaseTerm: '',
        ePlatform: 'Cortts Website, Nigerian Property Centre, Commercial website',
        floor: '10',
        availFloor: '7th Floor',
        link: 'Owner',
        linkContact: '+234800000000',
        corttsAgent: 'Anita',
        features: 'Fitted Kitchen, Elevator, Swimming pool, Gym,24 hour security and power, Water treatment plant.',
        desc: 'This property is just big jare there is nothing appealing here, nonsense, SMH. Na wa for the landlord chai!! ',
        remark: 'I swear the property is just too expensive is just too expensive funny landlord.',
    },
    {
        key: '14',
        title: 'Guru\'s Estate',
        area: 'Parkview ',
        date: '30 Feb, 2019',
        category: 'Commercial',
        pType: 'Semi-detached house',
        section: 'sale',
        price: '20,000,000',
        service: '500,000',
        Caution: '600,000',
        beds: '2',
        baths: '3',
        park: '3',
        landSize: '3000sqm',
        propSize: '1800sqm',
        location: '7b Furo Ezimora Street, Lekki Phase 1, Lagos.',
        nearPlace: 'Standard Chartterd bank, Lekki Collisium, Peninsula Hotel, Furn Truf, Ebeano Supermarket....',
        status: 'Completed',
        pTitle: 'C of O',
        leaseTerm: '',
        ePlatform: 'Cortts Website, Nigerian Property Centre, Commercial website',
        floor: '10',
        availFloor: '7th Floor',
        link: 'Owner',
        linkContact: '+234800000000',
        corttsAgent: 'Anita',
        features: 'Fitted Kitchen, Elevator, Swimming pool, Gym,24 hour security and power, Water treatment plant.',
        desc: 'This property is just big jare there is nothing appealing here, nonsense, SMH. Na wa for the landlord chai!! ',
        remark: 'I swear the property is just too expensive is just too expensive funny landlord.',
    },
];